services:
  test:
    image: debian:bookworm
    command: sleep infinity
    container_name: test
    user: 501:501
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./subdir:/var/www/html/subdir